// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
//
// API docs from [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web).
// Attributions and copyright licensing by Mozilla Contributors is licensed
// under [CC-BY-SA 2.5](https://creativecommons.org/licenses/by-sa/2.5/.

// Generated from Web IDL definitions.

// ignore_for_file: unintended_html_in_doc_comment

@JS()
library;

import 'dart:js_interop';

import 'html.dart';

typedef EventListener = JSFunction;

/// The **`Event`** interface represents an event which takes place on an
/// [`EventTarget`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget).
///
/// An event can be triggered by the user action e.g. clicking the mouse button
/// or tapping keyboard, or generated by APIs to represent the progress of an
/// asynchronous task. It can also be triggered programmatically, such as by
/// calling the
/// [`HTMLElement.click()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click)
/// method of an element, or by defining the event, then sending it to a
/// specified target using
/// [`EventTarget.dispatchEvent()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent).
///
/// There are many types of events, some of which use other interfaces based on
/// the main `Event` interface. `Event` itself contains the properties and
/// methods which are common to all events.
///
/// Many DOM elements can be set up to accept (or "listen" for) these events,
/// and execute code in response to process (or "handle") them. Event-handlers
/// are usually connected (or "attached") to various
/// [HTML elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
/// (such as `<button>`, `<div>`, `<span>`, etc.) using
/// [`EventTarget.addEventListener()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener),
/// and this generally replaces using the old HTML
/// [event handler attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes).
/// Further, when properly added, such handlers can also be disconnected if
/// needed using
/// [`removeEventListener()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener).
///
/// > [!NOTE]
/// > One element can have several such handlers, even for the exact same
/// > event—particularly if separate, independent code modules attach them, each
/// > for its own independent purposes. (For example, a webpage with an
/// > advertising-module and statistics-module both monitoring video-watching.)
///
/// When there are many nested elements, each with its own handler(s), event
/// processing can become very complicated—especially where a parent element
/// receives the very same event as its child elements because "spatially" they
/// overlap so the event technically occurs in both, and the processing order of
/// such events depends on the
/// [Event bubbling](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Event_bubbling)
/// settings of each handler triggered.
///
/// ---
///
/// API documentation sourced from
/// [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Event).
extension type Event._(JSObject _) implements JSObject {
  external factory Event(
    String type, [
    EventInit eventInitDict,
  ]);

  static const int NONE = 0;

  static const int CAPTURING_PHASE = 1;

  static const int AT_TARGET = 2;

  static const int BUBBLING_PHASE = 3;

  /// The **`composedPath()`** method of the [Event]
  /// interface returns the event's path which is an array of the objects on
  /// which listeners
  /// will be invoked. This does not include nodes in shadow trees if the shadow
  /// root was
  /// created with its [ShadowRoot.mode] closed.
  external JSArray<EventTarget> composedPath();

  /// The **`stopPropagation()`** method of the [Event]
  /// interface prevents further propagation of the current event in the
  /// capturing and
  /// bubbling phases. It does not, however, prevent any default behaviors from
  /// occurring; for
  /// instance, clicks on links are still processed. If you want to stop those
  /// behaviors, see
  /// the [Event.preventDefault] method. It also does not
  /// prevent propagation to other event-handlers of the current element. If you
  /// want to stop those,
  /// see [Event.stopImmediatePropagation].
  external void stopPropagation();

  /// The **`stopImmediatePropagation()`** method of the
  /// [Event] interface prevents other listeners of the same event from being
  /// called.
  ///
  /// If several listeners are attached to the same element for the same event
  /// type, they are called in the order in which they were added. If
  /// `stopImmediatePropagation()` is invoked during one such call, no remaining
  /// listeners will be called, either on that element or any other element.
  external void stopImmediatePropagation();

  /// The **`preventDefault()`** method of the [Event] interface tells the  that
  /// if the event does not get explicitly handled, its default action should
  /// not be taken as it normally would be.
  ///
  /// The event continues to propagate as usual,
  /// unless one of its event listeners calls
  /// [Event.stopPropagation]
  /// or [Event.stopImmediatePropagation],
  /// either of which terminates propagation at once.
  ///
  /// As noted below, calling **`preventDefault()`** for a
  /// non-cancelable event, such as one dispatched via
  /// [EventTarget.dispatchEvent], without specifying
  /// `cancelable: true` has no effect.
  ///
  /// If a passive listener calls `preventDefault()`, nothing will happen and a
  /// console warning may be generated.
  external void preventDefault();

  /// The **`Event.initEvent()`** method is used to initialize the
  /// value of an [event] created using [Document.createEvent].
  ///
  /// Events initialized in this way must have been created with the
  /// [Document.createEvent] method.
  /// This method must be called to set the event
  /// before it is dispatched, using [EventTarget.dispatchEvent].
  /// Once dispatched, it doesn't do anything anymore.
  ///
  /// > **Note:** _Do not use this method anymore as it is deprecated._
  /// > Instead use specific event constructors, like [Event.Event].
  /// > The page on
  /// > [Creating and triggering events](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events)
  /// > gives more information about the way to use these.
  external void initEvent(
    String type, [
    bool bubbles,
    bool cancelable,
  ]);

  /// The **`type`** read-only property of the [Event]
  /// interface returns a string containing the event's type. It is set when the
  /// event is
  /// constructed and is the name commonly used to refer to the specific event,
  /// such as
  /// `click`, `load`, or `error`.
  external String get type;

  /// The read-only **`target`** property of the
  /// [Event] interface is a reference to the object onto which the event was
  /// dispatched. It is different from [Event.currentTarget] when the event
  /// handler is called during the bubbling or capturing phase of the event.
  external EventTarget? get target;

  /// The deprecated **`Event.srcElement`** is an alias for the [Event.target]
  /// property. Use [Event.target] instead.
  external EventTarget? get srcElement;

  /// The **`currentTarget`** read-only property of the [Event] interface
  /// identifies the element to which the event handler has been attached.
  ///
  /// This will not always be the same as the element on which the event was
  /// fired, because the event may have fired on a descendant of the element
  /// with the handler, and then
  /// [bubbled](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Event_bubbling)
  /// up to the element with the handler. The element on which the event was
  /// fired is given by [Event.target].
  ///
  /// Note that the value of `currentTarget` is only available in a handler for
  /// the event. Outside an event handler it will be `null`. This means that,
  /// for example, if you take a reference to the `Event` object inside an event
  /// handler and then access its `currentTarget` property outside the event
  /// handler, its value will be `null`.
  external EventTarget? get currentTarget;

  /// The **`eventPhase`** read-only property of the
  /// [Event] interface indicates which phase of the event flow is currently
  /// being evaluated.
  external int get eventPhase;

  /// The **`cancelBubble`** property of the [Event]
  /// interface is deprecated. Use [Event.stopPropagation] instead.
  /// Setting its value to `true` before returning from an event handler
  /// prevents propagation
  /// of the event. In later implementations, setting this to `false` does
  /// nothing.
  /// See [Browser compatibility](#browser_compatibility) for details.
  external bool get cancelBubble;
  external set cancelBubble(bool value);

  /// The **`bubbles`** read-only property of the [Event] interface indicates
  /// whether the event bubbles up through the DOM tree or not.
  ///
  /// > [!NOTE]
  /// > See
  /// > [Event bubbling](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Event_bubbling)
  /// > for more information on bubbling.
  external bool get bubbles;

  /// The **`cancelable`** read-only property of the [Event] interface indicates
  /// whether the event
  /// can be canceled, and therefore prevented as if the event never happened.
  ///
  /// If the event is _not_ cancelable, then its `cancelable` property will be
  /// `false` and the event listener cannot stop the event from occurring.
  ///
  /// Most browser-native events that can be canceled are the ones that result
  /// from the user
  /// interacting with the page. Canceling the [Element.click_event],
  /// [Element.wheel_event], or
  /// [Window.beforeunload_event] events would prevent the user
  /// from clicking on something, scrolling the page with the mouse wheel, or
  /// navigating away from the page, respectively.
  ///
  /// [Synthetic events](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event)
  /// created by other JavaScript
  /// code define if they can be canceled when they are created.
  ///
  /// To cancel an event, call the [event.preventDefault]
  /// method on the event. This keeps the implementation from executing the
  /// default action
  /// that is associated with the event.
  ///
  /// Event listeners that handle multiple kinds of events may want to check
  /// `cancelable` before invoking their [event.preventDefault] methods.
  external bool get cancelable;

  /// The [Event] property
  /// **`returnValue`** indicates whether the default action for
  /// this event has been prevented or not.
  ///
  /// It is set to `true` by
  /// default, allowing the default action to occur. Setting this property to
  /// `false` prevents the default action.
  ///
  /// > [!NOTE]
  /// > While `returnValue` has been adopted into the DOM
  /// > standard, it is present primarily to support existing code. Use
  /// > [Event.preventDefault], and
  /// > [Event.defaultPrevented] instead of this historical
  /// > property.
  external bool get returnValue;
  external set returnValue(bool value);

  /// The **`defaultPrevented`** read-only property of the [Event] interface
  /// returns a boolean value indicating whether or not the call to
  /// [Event.preventDefault] canceled the event.
  external bool get defaultPrevented;

  /// The read-only **`composed`** property of the
  /// [Event] interface returns a boolean value which indicates whether
  /// or not the event will propagate across the shadow DOM boundary into the
  /// standard DOM.
  ///
  /// All UA-dispatched UI events are composed
  /// (click/touch/mouseover/copy/paste, etc.). Most
  /// other types of events are not composed, and so will return `false`. For
  /// example, this includes synthetic events that are created without their
  /// `composed` option set to `true`.
  ///
  /// Propagation only occurs if the [Event.bubbles] property is also
  /// `true`. However, capturing only composed events are also handled at host
  /// as
  /// if they were in `AT_TARGET` phase. You can determine the path the event
  /// will
  /// follow through the shadow root to the DOM root by calling
  /// [Event.composedPath].
  external bool get composed;

  /// The **`isTrusted`** read-only property of the
  /// [Event] interface is a boolean value that is `true`
  /// when the event was generated by the user agent (including via user actions
  /// and programmatic methods such as [HTMLElement.focus]),
  /// and `false` when the event was dispatched via
  /// [EventTarget.dispatchEvent].
  /// The only exception is the `click` event, which initializes the `isTrusted`
  /// property to `false` in user agents.
  external bool get isTrusted;

  /// The **`timeStamp`** read-only property of the [Event] interface returns
  /// the time (in milliseconds) at which the event was created.
  external double get timeStamp;
}
extension type EventInit._(JSObject _) implements JSObject {
  external factory EventInit({
    bool bubbles,
    bool cancelable,
    bool composed,
  });

  external bool get bubbles;
  external set bubbles(bool value);
  external bool get cancelable;
  external set cancelable(bool value);
  external bool get composed;
  external set composed(bool value);
}

/// The **`EventTarget`** interface is implemented by objects that can receive
/// events and may have listeners for them.
/// In other words, any target of events implements the three methods associated
/// with this interface.
///
/// [Element], and its children, as well as [Document] and [Window], are the
/// most common event targets,
/// but other objects can be event targets, too.
/// For example [IDBRequest], [AudioNode], and [AudioContext] are also event
/// targets.
///
/// Many event targets (including elements, documents, and windows) also support
/// setting
/// [event handlers](https://developer.mozilla.org/en-US/docs/Web/Events/Event_handlers)
/// via `onevent` properties and attributes.
///
/// ---
///
/// API documentation sourced from
/// [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget).
extension type EventTarget._(JSObject _) implements JSObject {
  external factory EventTarget();

  /// The **`addEventListener()`** method of the [EventTarget] interface
  /// sets up a function that will be called whenever the specified event is
  /// delivered to the target.
  ///
  /// Common targets are [Element], or its children, [Document], and [Window],
  /// but the target may be any object that supports events (such as
  /// [IDBRequest]).
  ///
  /// > [!NOTE]
  /// > The `addEventListener()` method is the _recommended_ way to register an
  /// > event listener. The benefits are as follows:
  /// >
  /// > - It allows adding more than one handler for an event. This is
  /// > particularly
  /// > useful for libraries, JavaScript modules, or any other kind of
  /// > code that needs to work well with other libraries or extensions.
  /// > - In contrast to using an `onXYZ` property, it gives you finer-grained
  /// > control of the phase when the listener is activated (capturing vs.
  /// > bubbling).
  /// > - It works on any event target, not just HTML or SVG elements.
  ///
  /// The method `addEventListener()` works by adding a function, or an object
  /// that implements a `handleEvent()` function, to the list of event listeners
  /// for the specified event type
  /// on the [EventTarget] on which it's called. If the function or object is
  /// already in the list of event listeners for this target, the function or
  /// object is not added a second time.
  ///
  /// > [!NOTE]
  /// > If a particular anonymous function is in the list of event listeners
  /// > registered for a certain target, and then later in the code, an
  /// > identical anonymous function is given in an `addEventListener` call, the
  /// > second function will _also_ be added to the list of event listeners for
  /// > that target.
  /// >
  /// > Indeed, anonymous functions are not identical even if defined using
  /// > the _same_ unchanging source-code called repeatedly, **even if in a
  /// > loop**.
  /// >
  /// > Repeatedly defining the same unnamed function in such cases can be
  /// > problematic. (See [Memory issues](#memory_issues), below.)
  ///
  /// If an event listener is added to an [EventTarget] from inside another
  /// listener —
  /// that is, during the processing of the event —
  /// that event will not trigger the new listener.
  /// However, the new listener may be triggered during a later stage of event
  /// flow,
  /// such as during the bubbling phase.
  external void addEventListener(
    String type,
    EventListener? callback, [
    JSAny options,
  ]);

  /// The **`removeEventListener()`** method of the [EventTarget] interface
  /// removes an event listener previously registered with
  /// [EventTarget.addEventListener] from the target.
  /// The event listener to be removed is identified using a combination of the
  /// event type,
  /// the event listener function itself, and various optional options that may
  /// affect the matching process;
  /// see
  /// [Matching event listeners for removal](#matching_event_listeners_for_removal).
  ///
  /// Calling `removeEventListener()` with arguments that do not identify any
  /// currently registered
  /// [event listener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#the_event_listener_callback)
  /// on the `EventTarget` has no
  /// effect.
  ///
  /// If an
  /// [event listener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#the_event_listener_callback)
  /// is removed from an [EventTarget] while another listener of the target is
  /// processing an event, it will not be triggered by the event. However, it
  /// can be reattached.
  ///
  /// > [!WARNING]
  /// > If a listener is registered twice, one with the _capture_ flag set and
  /// > one without, you must remove each one separately. Removal of a capturing
  /// > listener does not affect a non-capturing version of the same listener,
  /// > and vice versa.
  ///
  /// Event listeners can also be removed by passing an [AbortSignal] to an
  /// [EventTarget.addEventListener] and then later calling
  /// [AbortController.abort] on the controller owning the signal.
  external void removeEventListener(
    String type,
    EventListener? callback, [
    JSAny options,
  ]);

  /// The **`dispatchEvent()`** method of the [EventTarget] sends an [Event] to
  /// the object, (synchronously) invoking the affected
  /// event listeners in the appropriate order. The normal event processing
  /// rules (including the capturing and optional bubbling phase) also apply to
  /// events
  /// dispatched manually with `dispatchEvent()`.
  ///
  /// Calling `dispatchEvent()` is the last step to _firing an event_. The event
  /// should have already been created and initialized using an [Event.Event]
  /// constructor.
  ///
  /// > [!NOTE]
  /// > When calling this method, the [Event.target] property is initialized to
  /// > the current `EventTarget`.
  ///
  /// Unlike "native" events, which are fired by the browser and invoke event
  /// handlers
  /// asynchronously via the
  /// [event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop),
  /// `dispatchEvent()` invokes event handlers _synchronously_. All applicable
  /// event
  /// handlers are called and return before `dispatchEvent()` returns.
  external bool dispatchEvent(Event event);
}
extension type EventListenerOptions._(JSObject _) implements JSObject {
  external factory EventListenerOptions({bool capture});

  external bool get capture;
  external set capture(bool value);
}
extension type AddEventListenerOptions._(JSObject _)
    implements EventListenerOptions, JSObject {
  external factory AddEventListenerOptions({
    bool capture,
    bool passive,
    bool once,
    AbortSignal signal,
  });

  external bool get passive;
  external set passive(bool value);
  external bool get once;
  external set once(bool value);
  external AbortSignal get signal;
  external set signal(AbortSignal value);
}

/// The **`AbortSignal`** interface represents a signal object that allows you
/// to communicate with an asynchronous operation (such as a fetch request) and
/// abort it if required via an [AbortController] object.
///
/// ---
///
/// API documentation sourced from
/// [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal).
extension type AbortSignal._(JSObject _) implements EventTarget, JSObject {
  /// The **`AbortSignal.abort()`** static method returns an [AbortSignal] that
  /// is already set as aborted (and which does not trigger an
  /// [AbortSignal.abort_event] event).
  ///
  /// This is shorthand for the following code:
  ///
  /// ```js
  /// const controller = new AbortController();
  /// controller.abort();
  /// return controller.signal;
  /// ```
  ///
  /// This could, for example, be passed to a fetch method in order to run its
  /// abort logic (i.e. it may be that code is organized such that the abort
  /// logic should be run even if the intended fetch operation has not been
  /// started).
  ///
  /// > [!NOTE]
  /// > The method is similar in purpose to `Promise.reject`.
  external static AbortSignal abort([JSAny? reason]);

  /// The **`AbortSignal.timeout()`** static method returns an [AbortSignal]
  /// that will automatically abort after a specified time.
  ///
  /// The signal aborts with a `TimeoutError` [DOMException] on timeout.
  ///
  /// The timeout is based on active rather than elapsed time, and will
  /// effectively be paused if the code is running in a suspended worker, or
  /// while the document is in a back-forward cache
  /// ("[bfcache](https://web.dev/articles/bfcache)").
  ///
  /// To combine multiple signals, you can use [AbortSignal.any_static], for
  /// example, to directly abort a download using either a timeout signal or by
  /// calling [AbortController.abort].
  external static AbortSignal timeout(int milliseconds);

  /// The **`AbortSignal.any()`** static method takes an iterable of abort
  /// signals and returns an [AbortSignal]. The returned abort signal is aborted
  /// when any of the input iterable abort signals are aborted. The
  /// [AbortSignal.reason] will be set to the reason of the first signal that is
  /// aborted. If any of the given abort signals are already aborted then so
  /// will be the returned [AbortSignal].
  external static AbortSignal any(JSArray<AbortSignal> signals);

  /// The **`throwIfAborted()`** method throws the signal's abort
  /// [AbortSignal.reason] if the signal has been aborted; otherwise it does
  /// nothing.
  ///
  /// An API that needs to support aborting can accept an [AbortSignal] object
  /// and use `throwIfAborted()` to test and throw when the
  /// [`abort`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/abort_event)
  /// event is signalled.
  ///
  /// This method can also be used to abort operations at particular points in
  /// code, rather than passing to functions that take a signal.
  external void throwIfAborted();

  /// The **`aborted`** read-only property returns a value that indicates
  /// whether the asynchronous operations the signal is communicating with are
  /// aborted (`true`) or not (`false`).
  external bool get aborted;

  /// The **`reason`** read-only property returns a JavaScript value that
  /// indicates the abort reason.
  ///
  /// The property is `undefined` when the signal has not been aborted.
  /// It can be set to a specific value when the signal is aborted, using
  /// [AbortController.abort] or [AbortSignal.abort_static].
  /// If not explicitly set in those methods, it defaults to "AbortError"
  /// [DOMException].
  external JSAny? get reason;
  external EventHandler get onabort;
  external set onabort(EventHandler value);
}
